### ISSUE TITLE
Issue with Socket.io in Node 7

### ISSUE THREAD

**Issue by aendra-rininsland** [kavanagh/srvlr#1]
This might be PEBKAC but I'm getting the following when running Srvlr after upgrading to Node7:

```/usr/local/lib/node_modules/srvlr/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/srvlr/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/srvlr/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:573:32)```

**Comment by F1LT3R** [comment]
I am also having this issue in `markserv`: https://github.com/F1LT3R/markserv/issues/11
It's a known problem in `websocket.io`: https://github.com/LearnBoost/websocket.io/issues/55
It appears to originate in `robohydra`? https://github.com/robohydra/robohydra/issues/24

**Comment by callumlocke** [comment]
Seems this bug is already fixed in srvlr's master, but not published to npm.

@kavanagh can you publish a new version of srvlr?
`npm version minor && npm publish && git push && git push --tags`

**Comment by kavanagh** [comment]
Try now: version 0.7

**Comment by aendra-rininsland** [comment]
Confirming fixed; closing issue.
